symbols:
  - AAPL
  - MSFT
  - TSLA
  - NOK.OL
  - SAS.ST
  - SHOP.TO

rules:
  AND:
    - filter: rsi_filter
      period: 14
      threshold: 40
      direction: above
  OR:
    - filter: bollinger_filter
      period: 20
      std_dev: 2
      direction: below
