name: Check for Market Signals

on:
  schedule:
    # Runs every 5 minutes, Monday-Friday, between 7-16 UTC (9:00-18:00 Stockholm time).
    - cron: '*/5 7-16 * * 1-5'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the notifier script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIENT_EMAIL }}
        run: python notifier.py
